issuesOpened: >
  <img src="https://media.tenor.com/images/a44d0c84e5e535a649b16011b8d3c54c/tenor.gif" height=200 />
  
  Thank you for raising a issue. We will try and get back to you as soon as possible.

  Please make sure you have given us as much context as possible.

  Best,
  @Terrastories/terrastories-stewards 

pullRequestOpened: >
  <img src="https://media.giphy.com/media/LPx5F48jqLHd9ClF0L/giphy.gif" height=200 />
  
  Thank you for your pull request!
  
  Please make sure you have followed our (contributing guidelines)[CONTRIBUTING.md]. We will review it as soon as possible. 
  
  Best,
  @Terrastories/terrastories-stewards 