services:
  rails:
    image: ${DOCKER_IMAGE_NAME-terrastories}
    build:
      context: ./rails
    env_file:
      - .env
    command: scripts/server
    restart: always
    stdin_open: true
    tty: true
