services:
  rails:
    image: terrastories/devcore:latest
    build:
      context: ./rails
      target: devcore
    env_file:
      - .env
    command: scripts/server
    restart: unless-stopped
    stdin_open: true
    tty: true
