version: "3.4"
services:
  mariadb:
    restart: always
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - railroad
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    restart: always
    depends_on:
      - rails
      - tileserver
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - NODE_ENV=development
      - RAILS_ENV=development
    image: 'nginx:latest'
    networks:
      - tilenet
      - railroad
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

  rails:
    restart: always    
    build:
      context: ./rails
      target: prod
    image: terrastories/rails:prod
    labels:
      kompose.service.type: nodeport
    environment:
      - DATABASE_URL=mysql2://mariadb/terrastories_development
    depends_on:
      - tileserver
      - mariadb
    networks:
      - railroad
    tty: true # Enables debugging capabilities when attached to this container.
    volumes:
      - ./media:/media
      # - ./rails:/app
      - ./rails/nginx:/etc/nginx
      - yarn_cache:/usr/local/share/.cache
      - type: tmpfs
        target: /app/tmp/pids/

  tilebuilder:
    build:
      context: ./tilebuilder
    image: terrastories/tilebuilder
    network_mode: none
    volumes:
      - type: bind
        source: ./tilebuilder/script
        target: /script
      - type: volume
        source: mbtiles
        target: /data/mbtiles
      - type: bind
        source: ./tilebuilder/shapefiles
        target: /data/shapefiles

  tileserver:
    restart: always
    image: klokantech/tileserver-gl
    networks:
      - tilenet
    volumes:
      - type: bind
        source: ./tileserver/data
        target: /data
      - type: volume
        source: mbtiles
        target: /data/mbtiles

networks:
  railroad:
  tilenet:

volumes:
  mbtiles:
  dbdata:
  yarn_cache:

