version: "3.7"

services:
  tileserver:
    restart: always
    image: maptiler/tileserver-gl
    command: "-p 8080"
    ports:
      - 8080:8080
    expose:
      - "8080"
    volumes:
      - ./tileserver/data:/data
    environment:
      - VIRTUAL_HOST=tileserver.terrastories.local
      - VIRTUAL_PORT=8080

  web:
    environment:
      - USE_LOCAL_MAP_SERVER=true
      - OFFLINE_MAP_STYLE=http://tileserver.terrastories.local/styles/terrastories-map/style.json