version: "3.7"
services:

  tileserver:
    restart: always
    image: klokantech/tileserver-gl
    ports:
      - '8080:80'
    volumes:
      - type: bind
        source: ./tileserver/data
        target: /data

volumes:
  mbtiles:

