#!/bin/bash

# Install docker if not already installed
if [ "$(which docker)" == "" ]; then
  sudo apt-get install -y apt-transport-https ca-certificates software-properties-common

  # First, add the GPG key for the official Docker repository to the system:
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  # Add the Docker repository to APT sources:
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  # Next, update the package database with the Docker packages from the newly added repo:
  sudo apt-get update

  #Finally, install Docker:
  sudo apt-get install -y docker-ce
fi

# start docker service
service docker start

if [ "$(which docker-compose)" == "" ]; then
  sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /bin/docker-compose
  chmod a+x /bin/docker-compose
fi
