source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.10'

# lock mail version (required by rails)
# until upgrade to Ruby 3
gem 'mail', '2.7.1'
gem 'rails', '~> 6.1.0'
# Use Puma as the app server
gem 'puma', '~> 4.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# GeoJson / rgeo
gem 'rgeo', '~> 2.4.0'
gem 'rgeo-geojson', '~> 2.1.1'

# Geocoder for center calculation
gem 'geocoder', '~> 1.7.5'

# Use css_bundling for stylesheets
gem 'cssbundling-rails', '~> 1.1.2'

# Use Uglifier as compressor for JavaScript assets
gem 'terser', '~> 1.1.8'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use devise for authentication
gem 'devise', '~> 4.8.1'

# Use pundit for policy based authorization
gem 'pundit', '~> 2.2.0'

# Internationalization
gem 'rails-i18n', '~> 7.0.3'
gem 'devise-i18n', '~> 1.10.2'

# Mapbox GL rendering library
gem 'mapbox-gl-rails', '~> 2.9.0'

# S3 backed Active Storage
gem 'aws-sdk-s3', '~> 1.113.0'

# ActiveStorage Validation
gem 'activestorage-validator', '~> 0.2.0'

# Enable Webpack for javascript application code
gem 'webpacker', '~> 5.0'
gem 'react-rails', '~> 2.6.2'

# Use ActiveStorage variant
gem 'image_processing', '~> 1.12.2'

# Use Flipper for feature flags
gem 'flipper', '~> 0.25.3'
gem 'flipper-active_record', '~> 0.25.3'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
# gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'guard-rspec'
  gem 'shoulda-matchers'
  gem 'bundler-audit'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'

  # Add better error handling to make debugging simpler
  gem "better_errors"
  gem "binding_of_caller"

  # annotate models
  gem "annotate"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'webdrivers'
  # Factories for creating database entities for testing
  gem 'factory_bot_rails'
  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
