#!/bin/sh

if [ "$CHECK_BUNDLER" = "yes" ]
then
  bundle check || bundle install
fi

rm -f tmp/pids/server.pid

if [[ "$RAILS_ENV" == "offline" ]];
then
  bundle exec rake assets:precompile
fi

echo "Starting Rails Server..."
bundle exec rails server --binding 0.0.0.0
