name: Build and push devcore docker image

on:
  push:
    branches:
      - master
      - main

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        IMAGE_TAG: ${{ env.GITHUB_SHA }}
      with:
        context: "{{defaultContext}}:rails"
        target: devcore
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          terrastories/devcore:$IMAGE_TAG
          terrastories/devcore:latest