name: push-docker-development

on:
  pull_request:
    branches:
      - master

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:rails"
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: terrastories/terrastories:${{ github.ref_name }}
